---
baseurl: https://aras-p.info/
disablePathToLower: true
languageCode: en-us
title: Aras' website
copyright: "<small>Text content © Aras Pranckevičius. Code snippets are public domain, unless specified otherwise.</small>"
theme: aras
permalinks:
    blog: /blog/:year/:month/:day/:slug/
params:
    twitter: aras_p
    github: aras-p
    contact: mailto:aras@nesnausk.org
    ga_api_key: UA-299873-3
Paginate: 5

rssLimit: 50

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
  - name: title
    weight: 100
  - name: date
    weight: 10
  - name: tags
    weight: 80

menu:
  main:
      - Name: "Home"
        Weight: -150
        Identifier: "home"
        URL: "/"
      - Name: "Blog"
        Weight: -140
        Identifier: "blog"
        URL: "/blog/"
      - Name: "Talks"
        Weight: -130
        Identifier: "talks"
        URL: "/texts/talks.html"
      - Name: "Papers"
        Weight: -120
        Identifier: "texts"
        URL: "/texts"
      - Name: "Projects"
        Weight: -110
        Identifier: "proj"
        URL: "/proj.html"

blackfriday:
  fractions: false
...